main: com.izanagicraft.guard.IzanagiWorldGuardPlugin
name: IzanagiWorldGuard
version: ${version}
author:
  - sanguine6660
api-version: 1.20
description: ${description}
depend:
  - 'izanagi-librarian'
  - WorldEdit
  - FastAsyncWorldEdit
website: https://github.com/IzanagiCraft/IzanagiWorldGuard
load: STARTUP
